name: Build and Publish Container to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Authenticate with Azure
      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Install Azure ML Extension
      - name: Install Azure ML Extension
        run: az extension add --name ml

      # Step 4: Retrieve Model from Azure
      - name: Retrieve Model from Azure
        run: az ml model download --name "roberta-sequence" --version 1 --workspace-name "${{ secrets.AZURE_WORKSPACE_NAME }}" --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}"

      # Step 5: Move Model to Webapp Directory
      - name: Move Model to Webapp Directory
        run: mv roberta-sequence-classification-9.onnx ./webapp

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build and Push Flask-App Container
      - name: Build and Push Flask-App Container
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-roberta:latest
