name: Build and Package RoBERTa Sequencing to Dockerhub

on:
  # Trigger workflow on push to main branch
  push:
    branches:
      - main
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Authenticate with Azure
      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Install Azure ML Extension
      - name: Install Azure ML Extension
        run: az extension add --name ml

      # Step 4: Set auto-install of Azure extensions
      - name: Set Auto-Install of Azure Extensions
        run: az config set extension.use_dynamic_install=yes_without_prompt

      # Step 5: Download the Registered Model
      - name: Retrieve Model from Azure
        run: az ml model download --name "roberta-sequence" --version 1 --workspace-name "${{ secrets.AZURE_WORKSPACE_NAME }}" --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}"

      # Step 6: Build and Tag the Docker Container
      - name: Build Flask-App Container
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: nwaneri/flask-roberta:latest
